version: "3"
services:
  redis:
    image: redis
    container_name: ts_express_redis
    ports:
      - "6379:6379"
    networks:
      - ts_express

  # mongodb:
  #   image: mongo
  #   container_name: ts_express_mongodb
  #   ports:
  #     - "27020:27017" # avoiding conflicts
  #   volumes:
  #     - mongodb_data:/data/db
  #   networks:
  #     - ts_express

networks:
  ts_express:

volumes:
  mongodb_data:
